# Autogenerated by devscripts/update-version.py

__version__ = '2026.02.26.104931'

RELEASE_GIT_HEAD = 'eab6d6e795f26172aa5c1d60ecbb13cfc12e539a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Kenshin9977/yt-dlp'

ORIGIN = 'Kenshin9977/yt-dlp'

_pkg_version = '2026.02.26.104931'
