# Autogenerated by devscripts/update-version.py

__version__ = '2026.02.26.100903'

RELEASE_GIT_HEAD = 'd185652eb5fc8473742a61f3536573287afb78bb'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Kenshin9977/yt-dlp'

ORIGIN = 'Kenshin9977/yt-dlp'

_pkg_version = '2026.02.26.100903'
