# Autogenerated by devscripts/update-version.py

__version__ = '2026.02.26.140425'

RELEASE_GIT_HEAD = 'd353b66b4806632eda643876a304931fa1bb4bef'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Kenshin9977/yt-dlp'

ORIGIN = 'Kenshin9977/yt-dlp'

_pkg_version = '2026.02.26.140425'
